try {

  alert('Inicio de intentos de prueba');  // (1) <--

  // ...no hay errores aquÃ­

  alert('Fin de las ejecuciones de try');   // (2) <--

} catch (err) {

  alert('Se ignora catch porque no hay errores'); // (3)

}
